name: http_client
description: The http_client package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.2.0

dependencies:
  dio: ^5.4.0
  fast_immutable_collections: ^9.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  models:
    path: ../models
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2
  retrofit_generator: ^8.0.5
