name: localization
description: The Localization package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

flutter_intl:
  enabled: true
