name: storage
description: The storage package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.4.1

dependencies:
  hive: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  pro_lints: ^2.0.4
